### ISSUE TITLE
ch04/on_time_flask_template.py returns   pyelasticsearch.exceptions.ElasticHttpError: (400, 'illegal_argument_exception')

### ISSUE THREAD

**Issue by markucsb** [rjurney/Agile_Data_Code_2#58]
127.0.0.1 - - [07/Dec/2017 21:13:39] "GET /flights/search/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
ImmutableMultiDict([('Carrier', ''), ('FlightDate', '2015-02-01'), ('TailNum', ''), ('Origin', 'JFK'), ('Dest', 'LAX'), ('FlightNum', '')])
QUERY
 2015-02-01 JFK LAX
{"from": 0, "sort": [{"FlightDate": {"order": "asc", "ignore_unmapped": true}}, {"DepTime": {"order": "asc", "ignore_unmapped": true}}, {"Carrier": {"order": "asc", "ignore_unmapped": true}}, {"FlightNum": {"order": "asc", "ignore_unmapped": true}}, "_score"], "size": 15, "query": {"bool": {"must": [{"match": {"FlightDate": "2015-02-01"}}, {"match": {"Origin": "JFK"}}, {"match": {"Dest": "LAX"}}]}}}
GET /agile_data_science/_search [status:400 request:0.001s]
127.0.0.1 - - [07/Dec/2017 21:13:51] "GET /flights/search/?Carrier=&Origin=JFK&Dest=LAX&FlightDate=2015-02-01&TailNum=&FlightNum= HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Agile_Data_Code_2/ch04/web/on_time_flask_template.py", line 153, in search_flights
    results = elastic.search(query,index='agile_data_science')
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/pyelasticsearch/client.py", line 859, in search
    return self._search_or_count('_search', query, **kwargs)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/pyelasticsearch/client.py", line 836, in _search_or_count
    query_params=query_params)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/pyelasticsearch/client.py", line 285, in send_request
    self._raise_exception(status, error_message)
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/pyelasticsearch/client.py", line 299, in _raise_exception
    raise error_class(status, error_message)
pyelasticsearch.exceptions.ElasticHttpError: (400, 'illegal_argument_exception')
127.0.0.1 - - [07/Dec/2017 21:13:51] "GET /flights/search/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Dec/2017 21:13:51] "GET /flights/search/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [07/Dec/2017 21:13:51] "GET /flights/search/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Dec/2017 21:13:51] "GET /flights/search/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Dec/2017 21:13:52] "GET /flights/search/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [07/Dec/2017 21:13:52] "GET /flights/search/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by rjurney** [comment]
@markucsb I am able to reproduce locally. I am looking into it, but it seems to be this issue: https://github.com/elastic/elasticsearch-py/issues/718

**Comment by rjurney** [comment]
@ledgerW @markucsb I have downgraded Elasticsearch for both the Vagrant and EC2 images. Can you try again with the new build setup? This should be resolved, but if not I'll try again. Thanks!

**Comment by 10843** [comment]
@rjurney What version of ElasticSearch did you downgrade to?

Thx

**Comment by rjurney** [comment]
@10843 5.X but it doesn't fix things for me. Working on this.

**Comment by 10843** [comment]
I was able to get pyelasticsearch to work with elasticsearch 5.0.0.  I downgraded the library to use 5.0.0 versions as well.
I did have to alter your elasticsearch query syntax to exclude the “ignore_unmapped” tags as they are not supported in that version.

I am now working on updating the mappings to allow retrieval of values in text columns.

Eric

**Comment by rjurney** [comment]
Now using elasticsearch 5.6.1 to resolve this problem.
