### ISSUE TITLE
Unable to run code inside IPython Notebook

### ISSUE THREAD

**Issue by sonhmai** [rjurney/Agile_Data_Code_2#79]
I was able to connect to Jupyter notebook through :5000 on my computer (forwarded to EC2).
However, when I opened the Introduction to PySpark notebook, the status is constantly switched between 'Connected' and 'Connecting to Kernel' and I can't run any code.

Below is the log from the notebook server on EC2.

[I 10:20:06.686 NotebookApp] Adapting to protocol v5.1 for kernel 62827ece-131c-4bb5-9d8b-575b22592937
[E 10:20:06.686 NotebookApp] Uncaught exception in /api/kernels/62827ece-131c-4bb5-9d8b-575b22592937/channels
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda/lib/python3.5/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "/home/ubuntu/anaconda/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 262, in open
        super(ZMQChannelsHandler, self).open()
      File "/home/ubuntu/anaconda/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 176, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'

**Comment by rjurney** [comment]
Sorry for the late reply, but this should work again?
